name 'olyn_database'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_database'
description 'Configures and imports databases and database users from data bag items'
version '0.0.0'

provides 'olyn_percona::default'
provides 'olyn_percona::bootstrap'
provides 'olyn_percona::databases'
provides 'olyn_percona::install'
provides 'olyn_percona::repo'
provides 'olyn_percona::security'
provides 'olyn_percona::services'
provides 'olyn_percona::users'
recipe 'olyn_percona::default', 'Installs and configures Percona cluster on the server'
recipe 'olyn_percona::bootstrap', 'Bootstraps and initiates the Percona cluster'
recipe 'olyn_percona::databases', 'Creates and imports databases'
recipe 'olyn_percona::install', 'Installs Percona and configures files'
recipe 'olyn_percona::repo', 'Adds the Percona release repo and installs the Percona release manager'
recipe 'olyn_percona::security', 'Secures local install and sets root password'
recipe 'olyn_percona::services', 'Shared blocks for the Percona cookbook'
recipe 'olyn_percona::users', 'Creates database users'
