name 'olyn_database'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_database'
description 'Configures and imports databases and database users from data bag items'
version '0.0.0'

provides 'olyn_percona::default'
provides 'olyn_percona::databases'
provides 'olyn_percona::users'
recipe 'olyn_percona::default', 'Installs and configures Percona cluster on the server'
recipe 'olyn_percona::databases', 'Creates and imports databases'
recipe 'olyn_percona::users', 'Creates database users'
